// Code generated by scripts/generate-sqlite-schema.ts. DO NOT EDIT.
// Edit src/lib/db/schema.pg.ts and re-run `bun scripts/generate-sqlite-schema.ts`.
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { uuidv7 } from "./uuidv7";
import { isoTimestamp } from "./columns.sqlite";

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    email: text("email").notNull(),
    name: text("name"),
    passwordHash: text("passwordHash"),
    // Null without a password or for one predating this column. Not the credential account's
    // updatedAt: the env-seeded admin rewrites that row on every start.
    passwordChangedAt: isoTimestamp("passwordChangedAt"),
    role: text("role").notNull().default("user"),
    provider: text("provider"),
    subject: text("subject"),
    avatarUrl: text("avatarUrl"),
    status: text("status").notNull().default("active"),
    username: text("username"),
    displayUsername: text("displayUsername"),
    emailVerified: integer("emailVerified", { mode: "boolean" }).notNull().default(false),
    // Set by Better Auth's two-factor plugin once TOTP is verified; local accounts only.
    twoFactorEnabled: integer("twoFactorEnabled", { mode: "boolean" }).notNull().default(false),
    // Forward auth's opaque user id. Nullable: rows from raw SQL are filled by `ensureUserUuids`.
    uuid: text("uuid").$defaultFn(() => uuidv7()),
    // Written when a sign-in completes (lib/auth/last-sign-in.ts); null until the first one.
    lastSignInAt: isoTimestamp("lastSignInAt"),
    lastSignInMethod: text("lastSignInMethod"),
    // Display preferences that follow the account; null falls back to the browser's.
    timeZone: text("timeZone"),
    numberFormat: text("numberFormat"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    emailUnique: uniqueIndex("users_email_unique").on(table.email),
    uuidUnique: uniqueIndex("users_uuid_unique").on(table.uuid),
  }),
);

// Auth tables use camelCase DB columns to match Better Auth's Kysely adapter.
export const sessions = sqliteTable(
  "sessions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    token: text("token").notNull(),
    expiresAt: isoTimestamp("expiresAt").notNull(),
    ipAddress: text("ipAddress"),
    userAgent: text("userAgent"),
    // For OIDC back-channel logout. `sid` is unique only per issuer, hence the provider beside it.
    oidcProviderId: text("oidcProviderId"),
    oidcSid: text("oidcSid"),
    // An admin's "view as" preview; narrows this session only. Groups are a JSON array of ids.
    viewAsRole: text("viewAsRole"),
    viewAsGroupIds: text("viewAsGroupIds"),
    viewAsExpiresAt: isoTimestamp("viewAsExpiresAt"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    tokenUnique: uniqueIndex("sessions_token_unique").on(table.token),
    userIdx: index("sessions_user_idx").on(table.userId),
    oidcSessionIdx: index("sessions_oidc_session_idx").on(table.oidcProviderId, table.oidcSid),
  }),
);

export const accounts = sqliteTable(
  "accounts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    accountId: text("accountId").notNull(),
    providerId: text("providerId").notNull(),
    accessToken: text("accessToken"),
    refreshToken: text("refreshToken"),
    idToken: text("idToken"),
    accessTokenExpiresAt: isoTimestamp("accessTokenExpiresAt"),
    refreshTokenExpiresAt: isoTimestamp("refreshTokenExpiresAt"),
    scope: text("scope"),
    password: text("password"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    providerAccountIdx: uniqueIndex("accounts_provider_account_idx").on(
      table.providerId,
      table.accountId,
    ),
    userIdx: index("accounts_user_idx").on(table.userId),
  }),
);

export const verifications = sqliteTable("verifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: isoTimestamp("expiresAt").notNull(),
  createdAt: isoTimestamp("createdAt"),
  updatedAt: isoTimestamp("updatedAt"),
});

// Better Auth's `twoFactor` model. `secret` and `backupCodes` are encrypted by the plugin with the
// auth secret; the lockout columns cap consecutive wrong codes per account.
export const twoFactors = sqliteTable(
  "two_factors",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    secret: text("secret").notNull(),
    backupCodes: text("backupCodes").notNull(),
    verified: integer("verified", { mode: "boolean" }).notNull().default(true),
    failedVerificationCount: integer("failedVerificationCount").notNull().default(0),
    lockedUntil: isoTimestamp("lockedUntil"),
  },
  (table) => ({
    userUnique: uniqueIndex("two_factors_user_unique").on(table.userId),
  }),
);

// Better Auth's `passkey` model (@better-auth/passkey). `publicKey` is a COSE key, not a secret;
// `transports` is comma-separated. A credential is bound to the rpID it was made on, the Public
// URL's hostname, so changing that hostname orphans every row here.
export const passkeys = sqliteTable(
  "passkeys",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name"),
    publicKey: text("publicKey").notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    credentialID: text("credentialID").notNull(),
    counter: integer("counter").notNull(),
    deviceType: text("deviceType").notNull(),
    backedUp: integer("backedUp", { mode: "boolean" }).notNull(),
    transports: text("transports"),
    aaguid: text("aaguid"),
    createdAt: isoTimestamp("createdAt"),
  },
  (table) => ({
    credentialUnique: uniqueIndex("passkeys_credential_unique").on(table.credentialID),
    userIdx: index("passkeys_user_idx").on(table.userId),
  }),
);

export const oauthProviders = sqliteTable(
  "oauth_providers",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    type: text("type").notNull().default("oidc"),
    clientId: text("clientId").notNull(),
    clientSecret: text("clientSecret").notNull(),
    issuer: text("issuer"),
    authorizationUrl: text("authorizationUrl"),
    tokenUrl: text("tokenUrl"),
    userinfoUrl: text("userinfoUrl"),
    scopes: text("scopes").notNull().default("openid email profile"),
    autoLink: integer("autoLink", { mode: "boolean" }).notNull().default(false),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    source: text("source").notNull().default("ui"),
    // ── OIDC group mapping ────────────────────────────────────────────────
    // Claim holding the user's groups. Dot-separated paths address nested claims (e.g.
    // "resource_access.cpm.roles").
    groupsClaim: text("groupsClaim").notNull().default("groups"),
    // Convention prefix: with "CPM_", membership of "CPM_Admin" grants admin.
    groupPrefix: text("groupPrefix"),
    roleMappingEnabled: integer("roleMappingEnabled", { mode: "boolean" }).notNull().default(false),
    // Explicit overrides; when unset they are derived from groupPrefix.
    adminGroup: text("adminGroup"),
    operatorGroup: text("operatorGroup"),
    userGroup: text("userGroup"),
    viewerGroup: text("viewerGroup"),
    // Role assigned when no role group matched.
    defaultRole: text("defaultRole").notNull().default("user"),
    // Mirror the remaining prefixed IdP groups into CPM groups.
    syncGroups: integer("syncGroups", { mode: "boolean" }).notNull().default(false),
    // type='ldap' only (lib/ldap/config.ts); such a row borrows issuer, clientId and clientSecret.
    ldapConfig: text("ldapConfig"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("oauth_providers_name_unique").on(table.name),
  }),
);

export const oauthStates = sqliteTable(
  "oauth_states",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    state: text("state").notNull(),
    codeVerifier: text("codeVerifier").notNull(),
    redirectTo: text("redirectTo"),
    createdAt: text("createdAt").notNull(),
    expiresAt: text("expiresAt").notNull(),
  },
  (table) => ({
    stateUnique: uniqueIndex("oauth_state_unique").on(table.state),
  }),
);

export const pendingOAuthLinks = sqliteTable(
  "pending_oauth_links",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    provider: text("provider", { length: 50 }).notNull(),
    userEmail: text("userEmail").notNull(), // Email of the user who initiated linking
    createdAt: text("createdAt").notNull(),
    expiresAt: text("expiresAt").notNull(),
  },
  (table) => ({
    userProviderUnique: uniqueIndex("pending_oauth_user_provider_unique").on(
      table.userId,
      table.provider,
    ),
  }),
);

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

/**
 * Settings edited but not yet applied. Same shape as `settings`, so a staged row is a drop-in;
 * per user so one admin's apply never lands another's half-finished edits.
 */
export const settingsStaged = sqliteTable(
  "settings_staged",
  {
    key: text("key").notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    value: text("value").notNull(),
    stagedAt: text("stagedAt").notNull(),
  },
  (table) => ({
    pk: uniqueIndex("settings_staged_user_key_idx").on(table.userId, table.key),
  }),
);

/**
 * One row per apply. `summary` is rendered at apply time, since re-reading current values later
 * would narrate the present. `changes` (before/after JSON) is null on rows predating it.
 */
export const settingsRevisions = sqliteTable("settings_revisions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  appliedBy: integer("appliedBy").references(() => users.id, { onDelete: "set null" }),
  appliedByName: text("appliedByName"),
  summary: text("summary").notNull(),
  keys: text("keys").notNull(),
  changes: text("changes"),
  outcome: text("outcome").notNull(),
  error: text("error"),
  appliedAt: text("appliedAt").notNull(),
});

/**
 * Paired agents. No address: agents dial in, so reachability lives in `lib/agent/registry.ts`.
 * Pairing upserts on `agentId`, so a re-pair replaces the row.
 */
export const agents = sqliteTable(
  "agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    agentId: text("agentId").notNull(),
    /** Encrypted at rest. */
    secret: text("secret").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** JSON, or null to keep tracking the fleet default rather than a stale copy of it. */
    buildSettings: text("buildSettings"),
    lastSeenAt: text("lastSeenAt"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    agentIdUnique: uniqueIndex("agents_agentId_unique").on(table.agentId),
  }),
);

export const accessLists = sqliteTable("access_lists", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  description: text("description"),
  // What a request matching none of the IP rules gets; only consulted while there are rules.
  ipDefault: text("ipDefault").notNull().default("deny"),
  // "all": pass the IP rules and the password. "any": either will do.
  satisfy: text("satisfy").notNull().default("all"),
  // Forward the basic-auth Authorization header to the upstream.
  passAuth: integer("passAuth", { mode: "boolean" }).notNull().default(false),
  // What a denied request gets: null keeps 403. A redirect URL wins over the status and body.
  denyStatus: integer("denyStatus"),
  denyBody: text("denyBody"),
  denyRedirectUrl: text("denyRedirectUrl"),
  // Deny when the client address cannot be told apart from a trusted proxy's.
  failClosed: integer("failClosed", { mode: "boolean" }).notNull().default(false),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

export const accessListEntries = sqliteTable(
  "access_list_entries",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    accessListId: integer("accessListId")
      .references(() => accessLists.id, { onDelete: "cascade" })
      .notNull(),
    username: text("username").notNull(),
    passwordHash: text("passwordHash").notNull(),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    accessListIdIdx: index("access_list_entries_list_idx").on(table.accessListId),
  }),
);

/** Ordered allow/deny rules on the client; the first that matches decides. */
export const accessListIpRules = sqliteTable(
  "access_list_ip_rules",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    accessListId: integer("accessListId")
      .references(() => accessLists.id, { onDelete: "cascade" })
      .notNull(),
    action: text("action").notNull(),
    // Exactly one target. A hostname may end in /N, the IPv6 prefix its AAAA answers widen to.
    cidr: text("cidr"),
    hostname: text("hostname"),
    country: text("country"),
    continent: text("continent"),
    // Up to 2^32 - 1, past a PostgreSQL integer.
    asn: integer("asn"),
    note: text("note"),
    // Past it the rule is left out of the config, then deleted.
    expiresAt: text("expiresAt"),
    sortOrder: integer("sortOrder").notNull(),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    accessListIdIdx: index("access_list_ip_rules_list_idx").on(table.accessListId),
  }),
);

/**
 * What the hostnames in IP rules last resolved to, so a restart keeps the last known set. A cache:
 * never backed up, and rebuilt by the refresher (lib/access-lists/dns.ts).
 */
export const accessListDnsCache = sqliteTable("access_list_dns_cache", {
  hostname: text("hostname").primaryKey(),
  // JSON array of addresses; empty until a lookup succeeds, and again 24 h after the last one did.
  addresses: text("addresses").notNull(),
  resolvedAt: text("resolvedAt"),
  expiresAt: text("expiresAt").notNull(),
  lastError: text("lastError"),
  lastErrorAt: text("lastErrorAt"),
});

export const certificates = sqliteTable("certificates", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  domainNames: text("domainNames").notNull(),
  autoRenew: integer("autoRenew", { mode: "boolean" }).notNull().default(true),
  providerOptions: text("providerOptions"),
  certificatePem: text("certificatePem"),
  privateKeyPem: text("privateKeyPem"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
  /** `upload`, or `agent-file`: read by `sourceAgentId` from paths in its CERT_FILES_HOST_DIR. */
  source: text("source").notNull().default("upload"),
  /** Null once that agent is deleted: the last PEM stays, but no agent serves it. */
  sourceAgentId: integer("sourceAgentId").references(() => agents.id, { onDelete: "set null" }),
  sourceCertPath: text("sourceCertPath"),
  sourceKeyPath: text("sourceKeyPath"),
  sourceReadAt: text("sourceReadAt"),
  /** A `CertificateFileError` code; the last good PEM keeps serving meanwhile. */
  sourceError: text("sourceError"),
});

export const caCertificates = sqliteTable("ca_certificates", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  certificatePem: text("certificatePem").notNull(),
  privateKeyPem: text("privateKeyPem"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

export const issuedClientCertificates = sqliteTable(
  "issued_client_certificates",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    caCertificateId: integer("caCertificateId")
      .references(() => caCertificates.id, { onDelete: "cascade" })
      .notNull(),
    commonName: text("commonName").notNull(),
    serialNumber: text("serialNumber").notNull(),
    fingerprintSha256: text("fingerprintSha256").notNull(),
    certificatePem: text("certificatePem").notNull(),
    validFrom: text("validFrom").notNull(),
    validTo: text("validTo").notNull(),
    revokedAt: text("revokedAt"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    caCertificateIdx: index("issued_client_certificates_ca_idx").on(table.caCertificateId),
    revokedAtIdx: index("issued_client_certificates_revoked_at_idx").on(table.revokedAt),
  }),
);

export const proxyHosts = sqliteTable("proxy_hosts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  description: text("description"),
  /** JSON array, normalised on save; labels for finding hosts, never read by the config build. */
  tags: text("tags").notNull().default("[]"),
  domains: text("domains").notNull(),
  upstreams: text("upstreams").notNull(),
  certificateId: integer("certificateId").references(() => certificates.id, {
    onDelete: "set null",
  }),
  accessListId: integer("accessListId").references(() => accessLists.id, { onDelete: "set null" }),
  ownerUserId: integer("ownerUserId").references(() => users.id, { onDelete: "set null" }),
  sslForced: integer("sslForced", { mode: "boolean" }).notNull().default(true),
  hstsEnabled: integer("hstsEnabled", { mode: "boolean" }).notNull().default(true),
  hstsSubdomains: integer("hstsSubdomains", { mode: "boolean" }).notNull().default(false),
  allowWebsocket: integer("allowWebsocket", { mode: "boolean" }).notNull().default(true),
  preserveHostHeader: integer("preserveHostHeader", { mode: "boolean" }).notNull().default(true),
  meta: text("meta"),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
  skipHttpsHostnameValidation: integer("skipHttpsHostnameValidation", { mode: "boolean" })
    .notNull()
    .default(false),
});

export const apiTokens = sqliteTable(
  "api_tokens",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    tokenHash: text("tokenHash").notNull(),
    createdBy: integer("createdBy")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
    lastUsedAt: text("lastUsedAt"),
    expiresAt: text("expiresAt"),
    // "full", "read" or "custom"; a custom scope's permissions are a JSON array (lib/api-tokens).
    scope: text("scope").notNull().default("full"),
    permissions: text("permissions"),
  },
  (table) => ({
    tokenHashUnique: uniqueIndex("api_tokens_token_hash_unique").on(table.tokenHash),
  }),
);

export const auditEvents = sqliteTable(
  "audit_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    entityType: text("entityType").notNull(),
    entityId: integer("entityId"),
    summary: text("summary"),
    data: text("data"),
    createdAt: text("createdAt").notNull(),
    // The hash chain (lib/audit/chain.ts); all null on events written before it existed.
    // actorId copies userId without the foreign key, which nulls it when the user is deleted.
    actorId: integer("actorId"),
    seq: integer("seq"),
    prevHash: text("prevHash"),
    hash: text("hash"),
  },
  // The Overview's newest-first list and its server-events line both range over this.
  (table) => ({
    createdAtIdx: index("audit_events_created_at_idx").on(table.createdAt),
    seqIdx: uniqueIndex("audit_events_seq_idx").on(table.seq),
  }),
);

/** One row (id 1): the chain's head, locked by every chained insert, and where it starts. */
export const auditChain = sqliteTable("audit_chain", {
  id: integer("id").primaryKey(),
  headSeq: integer("headSeq").notNull(),
  headHash: text("headHash").notNull(),
  anchorSeq: integer("anchorSeq").notNull(),
  anchorHash: text("anchorHash").notNull(),
  // Events up to this id predate the chain and are not covered by it.
  legacyMaxId: integer("legacyMaxId").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

// traffic_events and waf_events live in ClickHouse (src/lib/clickhouse/client.ts); their parsers
// and offsets live in the agent, which is where the Caddy log file is.

// ── mTLS RBAC ──────────────────────────────────────────────────────────

export const mtlsRoles = sqliteTable(
  "mtls_roles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("mtls_roles_name_unique").on(table.name),
  }),
);

// Named SecLang snippets the global WAF and each host select by id (upstream #149).
export const wafPresets = sqliteTable(
  "waf_presets",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    directives: text("directives").notNull(),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("waf_presets_name_unique").on(table.name),
  }),
);

// CRS plugins installed from the plugin registry, pinned to the release they were fetched at. The
// rule files are stored rather than fetched per apply, so a config build never waits on GitHub.
export const crsPlugins = sqliteTable(
  "crs_plugins",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    repository: text("repository").notNull(),
    version: text("version").notNull(),
    description: text("description"),
    ruleIdStart: integer("ruleIdStart").notNull(),
    ruleIdEnd: integer("ruleIdEnd").notNull(),
    configRules: text("configRules").notNull(),
    beforeRules: text("beforeRules").notNull(),
    afterRules: text("afterRules").notNull(),
    // The operator's edit of the -config file; null runs the upstream one. Survives an update.
    configOverride: text("configOverride"),
    // JSON array of the plugins/ files the release had, for display; the rules are stored by kind.
    fileNames: text("fileNames").notNull().default("[]"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("crs_plugins_name_unique").on(table.name),
  }),
);

/** A WAF rule switched off globally or on one host, optionally under a path or for one variable. */
export const wafExclusions = sqliteTable(
  "waf_exclusions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ruleId: integer("ruleId").notNull(),
    /** Null is every host. */
    proxyHostId: integer("proxyHostId").references(() => proxyHosts.id, { onDelete: "cascade" }),
    /** Decoded and normalised; a trailing `*` is a prefix. */
    path: text("path"),
    /** A rule target such as `ARGS:content`, which the rule then skips. */
    target: text("target"),
    reason: text("reason").notNull().default(""),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    hostIdx: index("waf_exclusions_host_idx").on(table.proxyHostId),
  }),
);

/** A WAF event someone looked at. Events live in ClickHouse, so this keys them by content. */
export const wafEventReviews = sqliteTable(
  "waf_event_reviews",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    eventKey: text("eventKey").notNull(),
    /** `intended` or `false_positive`. */
    verdict: text("verdict").notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    eventKeyUnique: uniqueIndex("waf_event_reviews_event_key_unique").on(table.eventKey),
  }),
);

/** The global deny list, checked before every other handler on HTTP hosts. */
export const blockedSources = sqliteTable(
  "blocked_sources",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    /** `ip`, `cidr`, `country`, `continent` or `asn`. */
    kind: text("kind").notNull(),
    value: text("value").notNull(),
    reason: text("reason").notNull().default(""),
    /** Null never expires. */
    expiresAt: text("expiresAt"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    kindValueUnique: uniqueIndex("blocked_sources_kind_value_unique").on(table.kind, table.value),
    expiresAtIdx: index("blocked_sources_expires_at_idx").on(table.expiresAt),
  }),
);

export const mtlsCertificateRoles = sqliteTable(
  "mtls_certificate_roles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    issuedClientCertificateId: integer("issuedClientCertificateId")
      .references(() => issuedClientCertificates.id, { onDelete: "cascade" })
      .notNull(),
    mtlsRoleId: integer("mtlsRoleId")
      .references(() => mtlsRoles.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    certRoleUnique: uniqueIndex("mtls_cert_role_unique").on(
      table.issuedClientCertificateId,
      table.mtlsRoleId,
    ),
    roleIdx: index("mtls_certificate_roles_role_idx").on(table.mtlsRoleId),
  }),
);

export const mtlsAccessRules = sqliteTable(
  "mtls_access_rules",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    pathPattern: text("pathPattern").notNull(),
    allowedRoleIds: text("allowedRoleIds").notNull().default("[]"),
    allowedCertIds: text("allowedCertIds").notNull().default("[]"),
    denyAll: integer("denyAll", { mode: "boolean" }).notNull().default(false),
    priority: integer("priority").notNull().default(0),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    proxyHostIdx: index("mtls_access_rules_proxy_host_idx").on(table.proxyHostId),
    hostPathUnique: uniqueIndex("mtls_access_rules_host_path_unique").on(
      table.proxyHostId,
      table.pathPattern,
    ),
  }),
);

// ── Forward Auth (IdP) ───────────────────────────────────────────────

export const groups = sqliteTable(
  "groups",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    // "ui" for operator-managed groups, "oidc" for groups created by an IdP group sync. Only
    // "oidc" group membership is reconciled on sign-in.
    source: text("source").notNull().default("ui"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("groups_name_unique").on(table.name),
  }),
);

export const groupMembers = sqliteTable(
  "group_members",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    memberUnique: uniqueIndex("group_members_unique").on(table.groupId, table.userId),
    userIdx: index("group_members_user_idx").on(table.userId),
  }),
);

export const forwardAuthAccess = sqliteTable(
  "forward_auth_access",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "cascade" }),
    groupId: integer("groupId").references(() => groups.id, { onDelete: "cascade" }),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    hostIdx: index("faa_host_idx").on(table.proxyHostId),
    userUnique: uniqueIndex("faa_user_unique").on(table.proxyHostId, table.userId),
    groupUnique: uniqueIndex("faa_group_unique").on(table.proxyHostId, table.groupId),
  }),
);

export const forwardAuthSessions = sqliteTable(
  "forward_auth_sessions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    tokenHash: text("tokenHash").notNull(),
    expiresAt: text("expiresAt").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    tokenHashUnique: uniqueIndex("fas_token_hash_unique").on(table.tokenHash),
    userIdx: index("fas_user_idx").on(table.userId),
    proxyHostIdx: index("fas_proxy_host_idx").on(table.proxyHostId),
    expiresIdx: index("fas_expires_idx").on(table.expiresAt),
  }),
);

export const forwardAuthExchanges = sqliteTable(
  "forward_auth_exchanges",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    sessionId: integer("sessionId")
      .references(() => forwardAuthSessions.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    codeHash: text("codeHash").notNull(),
    // Legacy column holding a fixed placeholder; the real token is minted at redemption.
    sessionToken: text("sessionToken").notNull(),
    redirectUri: text("redirectUri").notNull(),
    expiresAt: text("expiresAt").notNull(),
    used: integer("used", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    codeHashUnique: uniqueIndex("fae_code_hash_unique").on(table.codeHash),
  }),
);

export const forwardAuthRedirectIntents = sqliteTable(
  "forward_auth_redirect_intents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ridHash: text("ridHash").notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    redirectUri: text("redirectUri").notNull(),
    expiresAt: text("expiresAt").notNull(),
    consumed: integer("consumed", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    ridHashUnique: uniqueIndex("fari_rid_hash_unique").on(table.ridHash),
    expiresIdx: index("fari_expires_idx").on(table.expiresAt),
  }),
);

// ── L4 Proxy Hosts ───────────────────────────────────────────────────

export const l4ProxyHosts = sqliteTable("l4_proxy_hosts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  description: text("description"),
  /** As on proxy_hosts. */
  tags: text("tags").notNull().default("[]"),
  protocol: text("protocol").notNull(),
  listenAddress: text("listenAddress").notNull(),
  upstreams: text("upstreams").notNull(),
  matcherType: text("matcherType").notNull().default("none"),
  matcherValue: text("matcherValue"),
  tlsTermination: integer("tlsTermination", { mode: "boolean" }).notNull().default(false),
  proxyProtocolVersion: text("proxyProtocolVersion"),
  proxyProtocolReceive: integer("proxyProtocolReceive", { mode: "boolean" })
    .notNull()
    .default(false),
  /** Its IP rules only. Deleting a list a host uses is refused by the model, not this key. */
  accessListId: integer("accessListId").references(() => accessLists.id, { onDelete: "set null" }),
  ownerUserId: integer("ownerUserId").references(() => users.id, { onDelete: "set null" }),
  meta: text("meta"),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

/**
 * Which agents serve a host; no rows means every agent, so upgrades change nothing. Many-to-many
 * because two edge nodes serving one host is ordinary HA.
 */
export const proxyHostAgents = sqliteTable(
  "proxy_host_agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    agentId: integer("agentId")
      .references(() => agents.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    pairUnique: uniqueIndex("proxy_host_agents_unique").on(table.proxyHostId, table.agentId),
    agentIdx: index("proxy_host_agents_agent_idx").on(table.agentId),
  }),
);

/** The same, for layer-4 hosts. Separate table because the two host tables are separate. */
export const l4ProxyHostAgents = sqliteTable(
  "l4_proxy_host_agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    l4ProxyHostId: integer("l4ProxyHostId")
      .references(() => l4ProxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    agentId: integer("agentId")
      .references(() => agents.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    pairUnique: uniqueIndex("l4_proxy_host_agents_unique").on(table.l4ProxyHostId, table.agentId),
    agentIdx: index("l4_proxy_host_agents_agent_idx").on(table.agentId),
  }),
);

/**
 * IdP group names mapped to a CPM group, for names the prefix convention cannot express. Null
 * `providerId` means any provider; uniqueness lives in the model since PostgreSQL treats NULLs
 * as distinct.
 */
export const groupIdpMappings = sqliteTable(
  "group_idp_mappings",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    providerId: text("providerId").references(() => oauthProviders.id, { onDelete: "cascade" }),
    /** As the operator typed it, for display. */
    externalName: text("externalName").notNull(),
    /** Lower-cased and path-stripped, which is what claims are compared against. */
    externalKey: text("externalKey").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    groupIdx: index("group_idp_mappings_group_idx").on(table.groupId),
    keyIdx: index("group_idp_mappings_key_idx").on(table.externalKey),
  }),
);

/**
 * What a group may manage. Additive, and only for `operator`s. One nullable column per resource
 * kind, not a polymorphic pair, so real foreign keys delete grants with their host.
 */
export const groupGrants = sqliteTable(
  "group_grants",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId").references(() => proxyHosts.id, { onDelete: "cascade" }),
    l4ProxyHostId: integer("l4ProxyHostId").references(() => l4ProxyHosts.id, {
      onDelete: "cascade",
    }),
    agentId: integer("agentId").references(() => agents.id, { onDelete: "cascade" }),
    /** "view" or "manage". A manage grant implies view. */
    capability: text("capability").notNull().default("manage"),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    groupIdx: index("group_grants_group_idx").on(table.groupId),
    proxyHostUnique: uniqueIndex("group_grants_proxy_host_unique").on(
      table.groupId,
      table.proxyHostId,
    ),
    l4HostUnique: uniqueIndex("group_grants_l4_host_unique").on(table.groupId, table.l4ProxyHostId),
    agentUnique: uniqueIndex("group_grants_agent_unique").on(table.groupId, table.agentId),
  }),
);

/** A browser an administrator turned notifications on in. The keys encrypt each push for it. */
export const pushSubscriptions = sqliteTable(
  "push_subscriptions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    /** The push service's URL for this browser; what the browser itself identifies it by. */
    endpoint: text("endpoint").notNull(),
    p256dh: text("p256dh").notNull(),
    auth: text("auth").notNull(),
    /** The reader's locale when they subscribed; a push has no request to negotiate one from. */
    locale: text("locale"),
    userAgent: text("userAgent"),
    /**
     * The session that turned it on. Not a foreign key: a session expiring must not stop pushes,
     * but revoking sessions (sign out others, a password change) takes their browsers with them.
     */
    sessionId: integer("sessionId"),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    endpointUnique: uniqueIndex("push_subscriptions_endpoint_unique").on(table.endpoint),
    userIdx: index("push_subscriptions_user_idx").on(table.userId),
  }),
);

/** A named analytics page state. Shared ones are listed for everyone who can open analytics. */
export const analyticsViews = sqliteTable(
  "analytics_views",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    name: text("name").notNull(),
    /** The page's query string, re-parsed on load, so an old view never bypasses sanitising. */
    query: text("query").notNull(),
    shared: integer("shared", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    userIdx: index("analytics_views_user_idx").on(table.userId),
  }),
);
