/** Self-signed EC pairs valid until 2126: A names two hosts, B one. Only their shape matters. */
export const CERT_A = `-----BEGIN CERTIFICATE-----
MIIBxjCCAWygAwIBAgIUdnzupUssDbUqoEzFpG71/NVd3RkwCgYIKoZIzj0EAwIw
HDEaMBgGA1UEAwwRZmlsZXMuZXhhbXBsZS5jb20wIBcNMjYwOTI4MTE0NjE1WhgP
MjEyNjA5MDQxMTQ2MTVaMBwxGjAYBgNVBAMMEWZpbGVzLmV4YW1wbGUuY29tMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDDHKLoB5+4NPJVJBJYe+kZhXzCXooBgW
co+qhg1o7LG9x2RbIg0nC8wsMZ2EKWpeRCEaIir244wqGz2WoeHdyKOBiTCBhjAd
BgNVHQ4EFgQU3oaumQAnb3RQZZoeoOXDAugxcKkwHwYDVR0jBBgwFoAU3oaumQAn
b3RQZZoeoOXDAugxcKkwDwYDVR0TAQH/BAUwAwEB/zAzBgNVHREELDAqghFmaWxl
cy5leGFtcGxlLmNvbYIVd3d3LmZpbGVzLmV4YW1wbGUuY29tMAoGCCqGSM49BAMC
A0gAMEUCIQC2JbyLKG5GrbnzKCcjowcqi5zNoAgn8WFcAPu3RKA4vQIgbYnC9TRs
K1o1I6bV2cYAKwdAq+DLD6YXESVexIhrHdU=
-----END CERTIFICATE-----`;

export const KEY_A = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQguUuUCKDX4/CUNO/x
OR7mGYDx96dGo0yBEviXF0Xpp5qhRANCAAQMMcougHn7g08lUkElh76RmFfMJeig
GBZyj6qGDWjssb3HZFsiDScLzCwxnYQpal5EIRoiKvbjjCobPZah4d3I
-----END PRIVATE KEY-----`;

export const CERT_B = `-----BEGIN CERTIFICATE-----
MIIBrDCCAVOgAwIBAgIUEiKOxhhc4vMKBvHGznyhLgG+yDcwCgYIKoZIzj0EAwIw
HDEaMBgGA1UEAwwRb3RoZXIuZXhhbXBsZS5jb20wIBcNMjYwOTI4MTE0NjE1WhgP
MjEyNjA5MDQxMTQ2MTVaMBwxGjAYBgNVBAMMEW90aGVyLmV4YW1wbGUuY29tMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1a5oggLT3sMNf2T19s91aD7Uh3fR0vc7
7XX+w3+g4dDXjygZDod4zUzQTYKHAthDuSuNmAFcXVp540A7/82Y+qNxMG8wHQYD
VR0OBBYEFB0yrV0yHuD/xv6R9Rm+OFZjC5t6MB8GA1UdIwQYMBaAFB0yrV0yHuD/
xv6R9Rm+OFZjC5t6MA8GA1UdEwEB/wQFMAMBAf8wHAYDVR0RBBUwE4IRb3RoZXIu
ZXhhbXBsZS5jb20wCgYIKoZIzj0EAwIDRwAwRAIgSOGbf/fDGHfrtYRPYu954sGy
E0uy/2mKiPGMzov5BPECIBXiRVRX5foE3iTZXKkGQ9ZOKXlOFzn5CcPiRfRFyabr
-----END CERTIFICATE-----`;

export const KEY_B = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg49/VeGmVEG2cZ/Ki
8pMoV/bCst+9cog6m9NdqBgNFOehRANCAATVrmiCAtPeww1/ZPX2z3VoPtSHd9HS
9zvtdf7Df6Dh0NePKBkOh3jNTNBNgocC2EO5K42YAVxdWnnjQDv/zZj6
-----END PRIVATE KEY-----`;
